/**
 * Seed / fallback catalogue.
 * Used to populate MongoDB on first connect, and served as-is when no
 * MONGODB_URI is configured, so the site is never empty.
 */

export const CATEGORIES = [
  { slug: 'makineri', label: 'Makineri', icon: 'exc', order: 1, active: true },
  { slug: 'kova', label: 'Kova & koka', icon: 'bucket', order: 2, active: true },
  { slug: 'hidraulik', label: 'Hidraulikë', icon: 'cyl', order: 3, active: true },
  { slug: 'motor', label: 'Motor & transmision', icon: 'eng', order: 4, active: true },
  { slug: 'ecje', label: 'Goma & zinxhirë', icon: 'track', order: 5, active: true },
]

export const PRODUCTS = [
  {
    ref: 'M-330',
    category: 'makineri',
    stock: 'makine',
    name: 'Ekskavator CAT 330 Hidraulik',
    short: 'Klasa 30 ton. Motor Cat C7.1 ~273 hp, gërmim deri ~7.2 m.',
    images: ['/assets/cat330.jpg'],
    tags: ['CAT', '30 ton', 'Hidraulik'],
    bullets: [
      'Motor Cat C7.1, rreth 273 hp, kursim karburanti',
      'Thellësi gërmimi deri rreth 7.2 m, kovë e madhe',
      'Teknologji Cat: Grade Assist, Payload',
      'Kabinë moderne me ekran 10 inç',
      'Gjendje pune, gati për kantier',
    ],
    specs: [
      { label: 'Motor', value: 'Cat C7.1 · ~273 hp' },
      { label: 'Thellësi gërmimi', value: 'deri ~7.2 m' },
      { label: 'Klasa', value: '30 ton' },
      { label: 'Kabina', value: 'Ekran 10", Grade Assist' },
    ],
    note: 'Çmimi dhe orët e punës jepen me kontakt. Shikimi në Zall-Herr.',
    badge: 'Klasa 30 ton',
    featured: true,
    active: true,
    order: 1,
  },
  {
    ref: 'M-DMP',
    category: 'makineri',
    stock: 'makine',
    name: 'Dumper Terex Benford 4x4',
    short: 'Skip rrotullues 180°, shkarkim hidraulik, kapacitet ~3 deri 6 ton.',
    images: [
      '/assets/dumper-front.jpg',
      '/assets/dumper-sidel.jpg',
      '/assets/dumper-sider.jpg',
      '/assets/dumper-back.jpg',
      '/assets/dumper-yard1.jpg',
      '/assets/dumper-yard2.jpg',
    ],
    tags: ['Terex', '4x4', 'Skip 180°'],
    bullets: [
      '4x4 me rrota të mëdha off-road, ecën në terren të vështirë',
      'Skip i madh me shkarkim hidraulik dhe rrotullim 180°',
      'Kapacitet rreth 3 deri 6 ton sipas modelit',
      'Motor diesel, i mirëmbajtur nga flotë profesionale',
      'Për dhe, zhavorr, rërë, beton dhe mbeturina',
    ],
    specs: [
      { label: 'Tërheqja', value: '4x4 off-road' },
      { label: 'Kapaciteti', value: '~3 deri 6 ton' },
      { label: 'Skipi', value: 'Hidraulik, rrotullues' },
      { label: 'Motori', value: 'Diesel, i mirëmbajtur' },
    ],
    note: 'I përdorur por solid. Çmimi me kontakt.',
    badge: 'Skip rrotullues 180°',
    featured: true,
    active: true,
    order: 2,
  },
  {
    ref: 'KV-01',
    category: 'kova',
    stock: 'stok',
    name: 'Kovë gërmimi me kapëse hidraulike',
    short: 'Lidhje e shpejtë me tuba hidraulikë, për ekskavatorë 20 deri 30 ton.',
    images: ['/assets/kova1.jpg'],
    tags: ['20-30 ton', 'Kapëse e shpejtë', 'Hidraulike'],
    bullets: [
      'Lidhje e shpejtë me tuba hidraulikë të montuar',
      'Për ekskavatorë të klasës 20 deri 30 ton',
      'Trup i fortë, i saldueshëm për riparim',
      'Përmasat e sakta dhe pini maten sipas kërkesës',
    ],
    specs: [],
    note: 'Na dërgoni markën dhe tonazhin e makinës për të konfirmuar përputhjen.',
    active: true,
    order: 3,
  },
  {
    ref: 'KV-02',
    category: 'kova',
    stock: 'stok',
    name: 'Kovë gërmimi 6 thumba',
    short: 'Kovë e gjerë me gjashtë thumba, për gërmim dheu dhe zhavorri.',
    images: ['/assets/kova2.jpg'],
    tags: ['6 thumba', 'Gërmim', 'E gjerë'],
    bullets: [
      'Gjashtë thumba në gjendje të përdorshme',
      'E përshtatshme për dhe, zhavorr dhe material të butë',
      'Gojëza dhe anët pa çarje',
      'Pini dhe gjerësia maten para dorëzimit',
    ],
    specs: [],
    note: 'Thumbat mund të ndërrohen me kërkesë, me kosto shtesë.',
    active: true,
    order: 4,
  },
  {
    ref: 'KV-03',
    category: 'kova',
    stock: 'stok',
    name: 'Kovë e rëndë me krah',
    short: 'Kovë e madhe së bashku me pjesën e krahut, për makineri të mëdha.',
    images: ['/assets/kova3.jpg'],
    tags: ['E rëndë', 'Me krah', 'Klasa e madhe'],
    bullets: [
      'Kovë e rëndë me pjesë krahu të bashkangjitur',
      'Për ekskavatorë të klasës së mesme dhe të madhe',
      'Shitet e plotë ose vetëm kova',
      'Foto shtesë të lidhjes dërgohen me kërkesë',
    ],
    specs: [],
    note: 'Pesha e lartë. Transporti organizohet me kamion.',
    active: true,
    order: 5,
  },
  {
    ref: 'KV-04',
    category: 'kova',
    stock: 'stok',
    name: 'Kovë kanali e ngushtë',
    short: 'Kovë e ngushtë me tre thumba, për hapje kanalesh dhe themele.',
    images: ['/assets/kova4.jpg'],
    tags: ['Kanal', '3 thumba', 'E ngushtë'],
    bullets: [
      'Profil i ngushtë për kanale dhe tubacione',
      'Tre thumba, gojëz e fortë',
      'Lidhje me dy pina standarde',
      'Ideale për punë uji, kabllo dhe themele',
    ],
    specs: [],
    note: 'Gjerësia e saktë matet dhe konfirmohet para shitjes.',
    active: true,
    order: 6,
  },
  {
    ref: 'KV-05',
    category: 'kova',
    stock: 'stok',
    name: 'Kovë gërmimi 5 thumba',
    short: 'Kovë e mesme me pesë thumba dhe lidhje me dy pina.',
    images: ['/assets/kova5.jpg'],
    tags: ['5 thumba', 'Klasa e mesme', 'Dy pina'],
    bullets: [
      'Pesë thumba, të gjithë në vend',
      'Për ekskavatorë të klasës së mesme',
      'Trup pa deformime të mëdha',
      'Gati për montim pas kontrollit të pinave',
    ],
    specs: [],
    note: 'Matjet e pinave jepen në WhatsApp sipas kërkesës.',
    active: true,
    order: 7,
  },
  {
    ref: 'HD-01',
    category: 'hidraulik',
    stock: 'porosi',
    name: 'Cilindër hidraulik krahu dhe kove',
    short: 'Cilindra të përdorur për ekskavatorë, në matje të ndryshme.',
    images: [],
    icon: 'cyl',
    tags: ['I përdorur', 'Matje të ndryshme'],
    bullets: [
      'Cilindra për krah, kovë dhe shul, sipas modelit',
      'Gjendja kontrollohet para dorëzimit',
      'Guarnicionet mund të ndërrohen me kërkesë',
      'Na dërgoni gjatësinë dhe diametrin e nevojshëm',
    ],
    specs: [],
    note: 'Foto dhe matje reale dërgohen në WhatsApp brenda ditës.',
    active: true,
    order: 8,
  },
  {
    ref: 'HD-02',
    category: 'hidraulik',
    stock: 'porosi',
    name: 'Pompë dhe distributor hidraulik',
    short: 'Pompa kryesore dhe distributorë të çmontuar nga makineri.',
    images: [],
    icon: 'pump',
    tags: ['Të çmontuara', 'Të testuara'],
    bullets: [
      'Pompa kryesore dhe distributorë nga makineri të çmontuara',
      'Marka dhe kodi i pjesës konfirmohen para shitjes',
      'Testim pamor dhe historiku i makinës',
      'Për CAT, Komatsu, JCB dhe të tjera',
    ],
    specs: [],
    note: 'Dërgoni kodin e pjesës ose foton e etiketës për konfirmim.',
    active: true,
    order: 9,
  },
  {
    ref: 'MT-01',
    category: 'motor',
    stock: 'porosi',
    name: 'Motor diesel i çmontuar',
    short: 'Motorë të plotë ose për pjesë, nga makineri ndërtimi.',
    images: [],
    icon: 'eng',
    tags: ['I plotë ose për pjesë', 'Diesel'],
    bullets: [
      'Motorë të plotë ose të çmontuar për pjesë',
      'Historiku i makinës nga e cila u hoq',
      'Blloqe, koka, pompa injeksioni dhe turbo',
      'Gjendja thuhet hapur para shitjes',
    ],
    specs: [],
    note: 'Na thoni markën, modelin dhe kodin e motorit.',
    active: true,
    order: 10,
  },
  {
    ref: 'MT-02',
    category: 'motor',
    stock: 'porosi',
    name: 'Reduktor ecjeje dhe rrotullimi',
    short: 'Final drive dhe swing motor për ekskavatorë me zinxhir.',
    images: [],
    icon: 'gear',
    tags: ['Final drive', 'Swing'],
    bullets: [
      'Reduktorë ecjeje dhe motorë rrotullimi',
      'Nga makineri të çmontuara te ne',
      'Kontroll i luftimit dhe i rrjedhjeve',
      'Për klasa nga 5 deri 35 ton',
    ],
    specs: [],
    note: 'Konfirmohet me numrin e modelit të makinës suaj.',
    active: true,
    order: 11,
  },
  {
    ref: 'EC-01',
    category: 'ecje',
    stock: 'stok',
    name: 'Zinxhirë dhe rula ekskavatori',
    short: 'Zinxhirë të plotë, rula, çarqe dhe ylli, për klasa të ndryshme.',
    images: [],
    icon: 'track',
    tags: ['Zinxhirë', 'Rula', 'Çarqe'],
    bullets: [
      'Zinxhirë të plotë dhe pjesë të veçanta',
      'Rula sipër dhe poshtë, çarqe, ylli',
      'Konsumimi matet dhe thuhet në përqindje',
      'Për ekskavatorë me zinxhir të klasave të ndryshme',
    ],
    specs: [],
    note: 'Na dërgoni numrin e hallkave dhe hapin e zinxhirit.',
    active: true,
    order: 12,
  },
  {
    ref: 'EC-02',
    category: 'ecje',
    stock: 'stok',
    name: 'Goma off-road për dumper dhe ngarkues',
    short: 'Goma të përdorura me profil të mirë, në matje të ndryshme.',
    images: [],
    icon: 'tire',
    tags: ['Off-road', 'Të përdorura'],
    bullets: [
      'Goma për dumper, ngarkues dhe traktorë',
      'Profili matet dhe fotografohet para shitjes',
      'Shiten copë ose në set',
      'Matje të ndryshme në stok',
    ],
    specs: [],
    note: 'Thoni matjen e gomës, p.sh. 405/70 R20.',
    active: true,
    order: 13,
  },
]

export const SETTINGS = {
  key: 'site',
  businessName: 'Makineri Lami',
  tagline: 'Pjesë & makineri',
  phone: '+355 68 615 6616',
  whatsapp: '355686156616',
  address: 'Zall-Herr, Tiranë',
  hours: 'Hën - Sht, 08:00 - 18:00',
  responseTime: 'Zakonisht brenda 24 orësh',
  heroEyebrow: 'Stok i ri çdo javë · Zall-Herr',
  heroTitle: 'Pjesë dhe makineri ndërtimi,',
  heroTitleAccent: 'gati për kantier.',
  heroLead:
    'Ekskavatorë, dumper, kova dhe pjesë këmbimi nga fusha jonë. Shtojini në listë dhe merrni çmimin me foto reale në WhatsApp, brenda ditës.',
  heroVideo: '/assets/hero.mp4',
  heroPoster: '/assets/hero-poster.jpg',
  yardImage: '/assets/yard.jpg',
  instagram: 'https://instagram.com/makineri.lami',
  facebook: 'https://www.facebook.com/profile.php?id=61579475937972',
  tiktok: 'https://www.tiktok.com/@makineri.lami',
  faq: [
    {
      q: 'Pse nuk ka çmime në faqe?',
      a: 'Sepse te pjesët e përdorura çmimi varet nga gjendja, sasia dhe modeli i saktë i makinës suaj. Një çmim i shtypur në faqe do të ishte i pasaktë për gjysmën e klientëve. Dërgoni listën në WhatsApp dhe merrni çmimin real brenda ditës.',
    },
    {
      q: 'A janë fotot reale apo nga interneti?',
      a: 'Të gjitha janë tonat, të bëra në fushën në Zall-Herr. Nëse doni foto shtesë të një detaji, të një saldimi ose të thumbave të kovës, e kërkoni në WhatsApp dhe jua dërgojmë po atë ditë.',
    },
    {
      q: 'A më shkon një kovë te makina ime?',
      a: 'Na thoni markën, modelin dhe tonazhin e ekskavatorit, ose fotografoni lidhjen, pinin dhe kapësin. Ju themi nëse përshtatet direkt, nëse duhet adapter, apo nëse ju sugjerojmë një alternativë tjetër nga stoku.',
    },
    {
      q: 'A bëni transport?',
      a: 'Po, transporti organizohet për të gjithë Shqipërinë, me kosto sipas destinacionit dhe peshës. Për pjesët e vogla përdorim edhe shërbimet e zakonshme të korrierit.',
    },
    {
      q: 'A mund të vij ta shoh makinerinë?',
      a: "Gjithmonë. Zall-Herr, Tiranë. Telefononi përpara që ta gjeni makinën të lirë dhe dikë në fushë t'jua tregojë në punë.",
    },
    {
      q: 'A pranoni këmbim ose blini makineri të vjetra?',
      a: 'Po, shqyrtojmë këmbim dhe blejmë makineri e pjesë të përdorura. Dërgoni foto dhe vitin e prodhimit në WhatsApp për një vlerësim fillestar.',
    },
  ],
}
